# https://docs.docker.com/compose/compose-file/05-services/
version: '3'

x-logging: &default-logging
    options:
        max-size: '10m'
        max-file: '3'

services:
    postgres:
        image: postgres:13.11
        profiles: ['infra']
        container_name: ${TYPEORM_HOST}
        environment:
            POSTGRES_DB: ${TYPEORM_DATABASE}
            POSTGRES_USER: ${TYPEORM_USERNAME}
            POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
        volumes:
            - ${DB_VOLUME_DIR:-/data/xrcloud-backend/postgres}:/var/lib/postgresql/data
        logging: *default-logging
        networks:
            - default

    redis:
        image: redis:7.0
        profiles: ['infra']
        container_name: ${CACHE_HOST}
        logging: *default-logging
        networks:
            - default

    service:
        image: ${DOCKER_IMAGE}
        build: .
        profiles: ['service']
        container_name: ${DOCKER_CONTAINER}
        environment:
            - NODE_ENV=production
        volumes:
            - ${ENV}:/app/.env
            - ${LOGS_DIR:-./logs}:/app/logs
            - ${STORAGE_DIR:-./app/xrcloud-backend/storage}:/app/xrcloud-backend/storage
        logging: *default-logging
        networks:
            - default

networks:
    default:
        external: true
        name: xrcloud
